Zero_Web/Controllers/AuthentificationController.cs
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.Cookies;
using Microsoft.Owin.Security.OpenIdConnect;
using MongoDB.Bson;
using System;
using System.Web;
using System.Web.Mvc;
using Zero_Web.Content.csharp.Zero;
using Zero_Web.Models;

namespace Zero_Web.Controllers
{
    public class AuthentificationController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registration(User user)
        {

            /*ToDo:
             Filter einbauen ob pw übereinstimmt..
            ob bereits account... somit kein 2.
            DBs aufteilen
             */

            //Create a Random UID for the User
            user.ID = Guid.NewGuid().ToString();

            //Hash Password
            HashPassword hashPassword = new HashPassword();
            user.Password = hashPassword.createHash(user.Password);
            user.ConfirmPassword = hashPassword.createHash(user.ConfirmPassword);

            //Store User Data in the DB
            database.MongoDBManager db = new database.MongoDBManager();
            db.createEntry("User", user.ToBsonDocument());

            //Clear all Registration Fields entered in the View
            ModelState.Clear();

            return View("Registration");//RedirectToAction("LogIn", "Account", new { area = "Admin" });
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult ForgotPassword()
        {
            return View();
        }

        public ActionResult ConfirmRegistration()
        {
            return View();
        }

        #region Microsoft
        /// <summary>
        /// Send an OpenID Connect sign-in request.
        /// Alternatively, you can just decorate the SignIn method with the [Authorize] attribute
        /// </summary>
        public void MS_SignIn()
        {
            if (!Request.IsAuthenticated)
            {
                HttpContext.GetOwinContext().Authentication.Challenge(
                    new AuthenticationProperties { RedirectUri = "/" },
                    OpenIdConnectAuthenticationDefaults.AuthenticationType);
            }
        }

        /// <summary>
        /// Send an OpenID Connect sign-out request.
        /// </summary>
        public void MS_SignOut()
        {
            HttpContext.GetOwinContext().Authentication.SignOut(
                    OpenIdConnectAuthenticationDefaults.AuthenticationType,
                    CookieAuthenticationDefaults.AuthenticationType);
        }
        #endregion

        #region Google
        /// <summary>
        /// Send an OpenID Connect sign-in request.
        /// Alternatively, you can just decorate the SignIn method with the [Authorize] attribute
        /// </summary>
        public void Google_SignIn()
        {
            if (!Request.IsAuthenticated)
            {
                HttpContext.GetOwinContext().Authentication.Challenge(
                    new AuthenticationProperties { RedirectUri = "/" },
                OpenIdConnectAuthenticationDefaults.AuthenticationType);
            }
        }

        /// <summary>
        /// Send an OpenID Connect sign-out request.
        /// </summary>
        public void Google_SignOut()
        {
            HttpContext.GetOwinContext().Authentication.SignOut(
                    OpenIdConnectAuthenticationDefaults.AuthenticationType,
                    CookieAuthenticationDefaults.AuthenticationType);
        }
        #endregion

        #region Facebook
        /// <summary>
        /// Send an OpenID Connect sign-in request.
        /// Alternatively, you can just decorate the SignIn method with the [Authorize] attribute
        /// </summary>
        public void Facebook_SignIn()
        {
            if (!Request.IsAuthenticated)
            {
                HttpContext.GetOwinContext().Authentication.Challenge(
                    new AuthenticationProperties { RedirectUri = "/" },
                    OpenIdConnectAuthenticationDefaults.AuthenticationType);
            }
        }

        /// <summary>
        /// Send an OpenID Connect sign-out request.
        /// </summary>
        public void Facebook_SignOut()
        {
            HttpContext.GetOwinContext().Authentication.SignOut(
                    OpenIdConnectAuthenticationDefaults.AuthenticationType,
                    CookieAuthenticationDefaults.AuthenticationType);
        }
        #endregion

    }
}

Zero_Web/Views/Authentification/ConfirmRegistration.cshtml
@model  Zero_Web.Models.User
@using Zero_Web.Variable;
@using Zero_Web.Resources.Login;

<head>
    <link href="~/Content/css/Authentification/ConfirmRegistration.css" rel="stylesheet">
    <link href="~/Content/css/Authentification/style.css" rel="stylesheet">
</head>

@{
    ViewBag.Title = "Confirm Registration";
}

<div class="ConfirmRegistrationBackground container-fluid">
    <img class="img-fluid w-100" src="@ImageSource.SVG.Login_Background" />
</div>

<div class="ConfirmRegistrationNav container-fluid d-flex flex-row-reverse pt-5">
    <div class="row float-right pr-5">
        <div class="row">
            <a href="@Url.Action("Login", "Authentification")" class="col-auto">@LanguageHandler.loadDBValueSettings("Login")</a>
            <img class="img-fluid col-md-3" src="~/Content/images/Zero/Logo_White.svg" />
        </div>
        <a href="#">@LanguageHandler.loadDBValueSettings("Back")</a>
    </div>
</div>

<div class="ConfirmRegistration container-fluid pt-5">

    <div class="pb-5 pl-3 pr-3">
        <div class="row justify-content-center">
            <img class="col-auto" src="@ImageSource.SVG.Logo_White" />
        </div>
        <div class="row justify-content-center">
            <p class="col">@LanguageHandler.loadDBValueSettings("ConfirmRegister_Heading")</p>
        </div>

        @using (Html.BeginForm())
        {

            <div class="row pl-5 pr-5 pt-3">
                <!--CHANGE TO CONFIRM KEY-->
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { placeholder = @Html.NameFor(model => model.Email), maxlength = "100", @class = "col justify-content-center" } })
                @*@Html.ValidationMessageFor(model => model.Email)*@
            </div>

            <div class="row pl-5 pr-5 pt-3">
                <p>@LanguageHandler.loadDBValueSettings("ConfirmRegister_ConfirmText")</p>
            </div>

            <div class="row pl-5 pr-5 pt-3">
                <!--CHANGE TO Check-->
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { placeholder = @Html.NameFor(model => model.Password), maxlength = "100", @class = "col justify-content-center" } })
                @*@Html.ValidationMessageFor(model => model.Password)*@
            </div>

            <div class="row justify-content-center pt-3 pl-5 pr-5">
                <input class="col" type="submit" value="@LanguageHandler.loadDBValueSettings("CreateAccount")">
            </div>
            
        }

        <div class="row justify-content-center">
            <a class="col">@LanguageHandler.loadDBValueSettings("ConfirmRegister_NewMail")</a>
            <a class="col">@LanguageHandler.loadDBValueSettings("ConfirmRegister_ChangeMail")</a>
        </div>

    </div>

</div>

Zero_Web/Views/Authentification/ForgotPassword.cshtml
@model  Zero_Web.Models.User

@{
    ViewBag.Title = "Forgot Password";
}

<div class="Zero Login">

    <h2>Zero Login</h2>
    <img src="~/Content/images/icons/icon-144x144.png" />

    @using (Html.BeginForm())
    {
        <div class="Zero Password">
            <div class="field">

                @Html.NameFor(model => model.Email)
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)

            </div>
            <input type="submit" value="ForgotPassword">
        </div>
    }
    @Html.ActionLink("Zurück zum Login", "Login", "Authentification")

</div>

<link href="~/Content/css/Authentification/Login.css" rel="stylesheet">
<link href="~/Content/css/Authentification/style.css" rel="stylesheet">